### ISSUE TITLE
After create cluster, pod/broker can not running

### ISSUE THREAD

**Issue by kangzemin** [apache/rocketmq-operator#109]
when I deploy rocketmq cluster,pod/broker is not ready,and restart always.
1. deploy step:
  1.1 git clone https://github.com/apache/rocketmq-operator.git
  1.2 cd rocketmq-operator
  1.3 checkout 0.2.1
  1.4 deployed ./deploy/crds/*
        deployed ./role & ./role_binding  & ./serviceaccount
        deployed ./operator
        waiting operator is running ,after: 
  1.5 deployed ./example/rocketmq_v1alpha1_rocketmq_cluster.yaml
        pod/name-service is running
        **but broker-0-master-0 is not ready,this is log:**
       
![image](https://user-images.githubusercontent.com/40269690/177495899-dcbcaabe-9937-43c7-a433-1804d4bc49c6.png)
![image](https://user-images.githubusercontent.com/40269690/177496092-ffb81df2-16d0-4fcd-8e58-fcc1cd4d3a9e.png)
2. Please tell us about your environment:
  kubernetes-version v1.20.0

**Comment by kangzemin** [comment]
> @kangzemin Please provide the output of `kubectl describe po broker-0-master-0 -n mq`, let's check what was wrong. It seems that the pod was killed due to OOM.
Thinks for your reply! this is output:
![image](https://user-images.githubusercontent.com/40269690/177525065-f48ae7ec-1e13-40df-99b5-4126cb67322b.png)
It looks like you're right.but why need so much resources?just a empty cluster, no data.
and, How can I solve this problem?

**Comment by caigy** [comment]
@kangzemin IMO configurations in example need to be modified. Please try setting `BROKER_MEM` to " -Xms1g -Xmx1g -Xmn512m " in the following files:
https://github.com/apache/rocketmq-operator/blob/f904c6604a58880d83444b25c4a331092737770a/example/rocketmq_v1alpha1_broker_cr.yaml#L21

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info**

The broker pod not becoming ready after cluster creation can have multiple causes. The screenshots referenced are not accessible in text form.

To diagnose, please provide:
- [ ] Output of `kubectl describe pod broker-0-master-0`
- [ ] Output of `kubectl logs broker-0-master-0`
- [ ] The RocketMQ cluster CR spec you deployed
- [ ] Kubernetes version and container runtime

Common causes include: incorrect storage configuration, missing PVC, or broker configuration mismatches.

---
*Automated evaluation by github-manager*
