### ISSUE TITLE
How to open acl support?

### ISSUE THREAD

**Issue by jackey20200402** [apache/rocketmq-operator#127]
The issue tracker is **ONLY** used for the bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before you raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by caigy** [comment]
You may try the following command or define it in configMap `broker-config`.
```sh
sh mqadmin updateBrokerConfig -c {YOUR_CLUSTER_NAME} -k aclEnable -v true
```

**Comment by jackey20200402** [comment]
开启ACL后如何修改plain_acl.yml，我尝试通过configMap 但不生效。
vim rocketmq_v1alpha1_rocketmq_cluster.yaml
volumes:
    - name: broker-config
      configMap:
        name: broker-config
        items:
          - key: broker-common.conf
            path: broker-common.conf
          - key: plain_acl.yml
            path: plain_acl.yml

**Comment by zongtanghu** [comment]
You can tell us the detailed steps for reappering the cases, maybe it can help us to find the cause!

**Comment by chixianliangGithub** [comment]
how to custiom plain_acl.yml content?
![image](https://github.com/apache/rocketmq-operator/assets/11659305/8d426484-05b0-48c9-a1cc-bd982bfef3b6)

**Comment by zhengbucuo888** [comment]
同问

**Comment by drivebyer** [comment]
We need support custom volumemount in broker.
