### ISSUE TITLE
构建指定版本的broker和namesrv镜像失败

### ISSUE THREAD

**Issue by go-xmyang** [apache/rocketmq-operator#138]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

cd images/namesrv/alpine
./build-namesrv-image.sh 4.9.3

- What did you expect to see?
镜像构建成功

- What did you see instead?
![image](https://user-images.githubusercontent.com/29217985/198770584-fd562797-6870-46a1-acce-f31c3a07a39d.png)

2. Please tell us about your environment:
![image](https://user-images.githubusercontent.com/29217985/198770803-ca8d98b0-4aeb-49b0-82fa-e6f5c1919e90.png)

**Comment by caigy** [comment]
@go-xmyang The distribution package of RocketMQ 4.9.3 does not match `rocketmq-all*` pattern, which is compatible with other versions. You can use 4.9.4 LTS version to bypass this problem. Also, would you like to fix the `dockerfile` so that  image of RocketMQ 4.9.3 can be built successfully?

**Comment by go-xmyang** [comment]
> 
好的，我很乐于尝试，如果修复了该问题，我会提交一个PR。

**Comment by caigy** [comment]
@go-xmyang Any updates?
