### ISSUE TITLE
install operator error happend with controller-gen No such file or directory

### ISSUE THREAD

**Issue by ggjjlldd** [apache/rocketmq-operator#139]
The issue tracker is **ONLY** used for the bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before you raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
-use command `make deploy` to install operator

- What did you expect to see?
install success
- What did you see instead?
controller-gen: No such file or directory
2. Please tell us about your environment:
```kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I use readme to install opeator, error happen say, controller-gen No such file or directory

**Comment by ggjjlldd** [comment]
I found solve method, use ` go mod tidy` first.

**Comment by caigy** [comment]
link #130

**Comment by caigy** [comment]
> I found solve method, use ` go mod tidy` first.

@ggjjlldd Great. Would you also like to improve the building part of README?
