### ISSUE TITLE
create broker cluster failed

### ISSUE THREAD

**Issue by jiangguiqiang199** [apache/rocketmq-operator#14]
execute this command:
kubectl apply -f example/rocketmq_v1alpha1_nameservice_cr.yaml 

get error:
Failed to update Broker Size status.

confused

**Comment by liuruiyiyang** [comment]
Could you please describe more context and details of the problem you encountered?  Or tell us  how to reproduce your issue(what have you done step by step). The command works fine in my environment if following the instruction of the README.

**Comment by vongosling** [comment]
This issue has been closed because it has not had activity in the last 30 days. If this issue is still valid, please ping a committer and ask them to label it as "help wanted". Thank you for your contributions.
