### ISSUE TITLE
rocketmq clients cannot access the broker

### ISSUE THREAD

**Issue by xinggengchang** [apache/rocketmq-operator#144]
1 error message : 
    2022-11-15 19:33:42.046  INFO   --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[] result: true
2 The network connection between the client and broker is abnormal
3 How do you solve this whole problem？

**Comment by caigy** [comment]
Pls provide more detailed info about this 'abnormal' situation.

**Comment by xinggengchang** [comment]
> Pls provide more detailed info about this 'abnormal' situation.

1 broker-0-master-0 ip is 10.233.127.180, broker-0-replica-1-0 ip is 10.233.127.181, node ip is 10.7.12.145，namesrvAddr is "10.7.12.145:9876"
2 The rocketmq client is on my local server，IP is 192.168.113.227
3 The client can connect to the nameservice but cannot connect to the broker,The broker ip is a pod ip not a real ip，so the network is unreachable。

**Comment by caigy** [comment]
> > Pls provide more detailed info about this 'abnormal' situation.
> 
> 1 broker-0-master-0 ip is 10.233.127.180, broker-0-replica-1-0 ip is 10.233.127.181, node ip is 10.7.12.145，namesrvAddr is "10.7.12.145:9876" 2 The rocketmq client is on my local server，IP is 192.168.113.227 3 The client can connect to the nameservice but cannot connect to the broker,The broker ip is a pod ip not a real ip，so the network is unreachable。

Have you also set `BrokerSpec.HostNetwork` to be `true`? It seems broker pods are not in host network.

**Comment by caigy** [comment]
@xinggengchang Are there any further information?

**Comment by caigy** [comment]
The issue may be stale and not active, I'll close it first.
