### ISSUE TITLE
5.0版本的rocketmq有对应编译好的crd可以使用么

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq-operator#146]
https://artifacthub.io/packages/olm/community-operators/rocketmq-operator
这个网址上面对应的rocketmq没有版本使用，报了如下错误信息：
error: unable to recognize "https://operatorhub.io/install/stable/rocketmq-operator.yaml": no matches for kind "Subscription" in version "operators.coreos.com/v1alpha1"

从https://artifacthub.io/页面上看到rocketmq-operator的使用量很低，是不能使用么

**Comment by caigy** [comment]
Is it issue about OLM? https://github.com/operator-framework/operator-lifecycle-manager/issues/854

**Comment by caigy** [comment]
As explained in [#5612](https://github.com/apache/rocketmq/issues/5612), it may be caused by unsuccessful deployment of  `Subscription` CR and rocketmq-opertor itself works fine.
If you still can't find a way to solve it, pls feel no hesitate to reopen this issue.
