### ISSUE TITLE
how to get mqadmin of arm64 version and share package exclusive problem?

### ISSUE THREAD

**Issue by bugme1024** [apache/rocketmq-operator#147]
Question 1: 
in operator contorller, it use belows tool to update Name service Addr.	
AdminToolDir = "/home/rocketmq/operator/bin/mqadmin"
but how to get arm version?

Question 2:

operator use share package some variables to share ( broker_cluster_name, name_srv_addr values), but how to solve the exclusive problem.

for example: two rocketmq cluster is being deploying at the same time.

**Comment by caigy** [comment]
Question 1: `mqadmin` itself is platform independent, but if the docker image of operator and RocketMQ need to be built on specified platform.

Question2: It seems that currently the implementation of share package brings exclusive problem, and variables of different clusters should be separated. Do you have any ideas to improve it ? @bugme1024

**Comment by caigy** [comment]
This issue seems to be stale, I'll close it first. Pls feel free to reopen it if further problems encountered.
