### ISSUE TITLE
Cannot access rocketmq from outside the k8s

### ISSUE THREAD

**Issue by Will-JZH** [apache/rocketmq-operator#15]
Hi, I have deployed rocketmq-operator but this rmq cannot be accessed from outside k8s. I know that the pod ip of broker is virtual and can only be accessed in the cluster. If we want to access the rocketmq through the outside of the k8s, is there a good way to solve this problem？
The error information is as follows:
![image](https://user-images.githubusercontent.com/25976014/71048794-6062c080-217b-11ea-94f0-5d6bca27754f.png)

**Comment by liuruiyiyang** [comment]
I am not sure what do you mean by ```"outside the k8s"```. Are the nodes running broker cluster and the client process are in the same network? And you can check the whether the client is using the correct IP addresses of namesrv pods.  RocketMq-Operator use the node IP as the IP of the pods by default if the nodes are not running out of yet.

**Comment by Will-JZH** [comment]
Client process and node running broker are not on the same network

**Comment by Will-JZH** [comment]
When I user `kubectl get pods -owide`:
![image](https://user-images.githubusercontent.com/25976014/72333102-38bd3480-36f6-11ea-8587-b2fb876a6258.png)

**Comment by Will-JZH** [comment]
Solved this problem by setting hostNetwork of broker is true. 
Close this issue.

**Comment by walk1ng** [comment]
> Solved this problem by setting hostNetwork of broker is true.
> Close this issue.

hi @zhihui921016 
could you please help to share how to achieve it? 
I have the same request as yours that our rocketmq clients(producer/consumer) run outside of the k8s which the rocketmq cluster running. 

thanks a lot!

**Comment by RobertoHuang** [comment]
have the same problem，how to solve it

**Comment by zhaozhihom** [comment]
> Solved this problem by setting hostNetwork of broker is true.
> Close this issue.

where the  hostNetwork should set, I set the rocketmq.apache.org/v1alpha1 Broker hostNetwork:true but not work

`apiVersion: rocketmq.apache.org/v1alpha1
kind: Broker
metadata:
  # name of broker cluster
  name: broker
spec:
  # size is the number of the broker cluster, each broker cluster contains a master broker and [replicaPerGroup] replica brokers.
  size: 1
  nameServers: ""
  replicaPerGroup: 1
  hostNetwork: true`
