### ISSUE TITLE
设置了hostNetwork，外部网络无法连接

### ISSUE THREAD

**Issue by 17736903561** [apache/rocketmq-operator#159]
通过连接nameserver 获取的 broker 的ip 是 pod 内网的ip，导致无法发送消息

**Comment by gzlboy** [comment]
> 通过连接nameserver 获取的 broker 的ip 是 pod 内网的ip，导致无法发送消息

和#157是一个问题

**Comment by caigy** [comment]
@gzlboy  Please discuss in #157, also check whether the brokers registered host addresses to name server and whether the host addresses were accessible from client side.
