### ISSUE TITLE
pod resources control and args needed

### ISSUE THREAD

**Issue by jasonz93** [apache/rocketmq-operator#16]
The opeator creates StatefulSet for namesrv and broker without resources settings, and args field is also unsupported; the official RoctetMQ image boot for over 8G memory as default, and leads to huge ops problem.

**Comment by liuruiyiyang** [comment]
Good point. We haven't add system resources settings in the CRDs yet which may be inconvenient when deploying on resource-limited environment. We will add system resources settings in the CRDs in the near future :)
