### ISSUE TITLE
No helm charts about this operator

### ISSUE THREAD

**Issue by drivebyer** [apache/rocketmq-operator#162]
Is there any plan to deploy this nice operator by helm?

**Comment by caigy** [comment]
There's helm charts deploying the pure docker images for RocketMQ (https://github.com/apache/rocketmq-docker/tree/master/rocketmq-k8s-helm), but no charts for deploying the RocketMQ CR and operator currently.

It would be nice if you can also involved in related work, welcome to contact me and participate in it.

**Comment by drivebyer** [comment]
> It would be nice if you can also involved in related work, welcome to contact me and participate in it.

Of course, I'm glad to

**Comment by caigy** [comment]
fixed by #165
