### ISSUE TITLE
why use ip for nameserver

### ISSUE THREAD

**Issue by lishitiancn** [apache/rocketmq-operator#17]
We can see that there are 1 name service Pods running on 1 nodes and their IP addresses. Modify the nameServers field in the rocketmq_v1alpha1_broker_cr.yaml file using the IP addresses.

**Comment by liuruiyiyang** [comment]
Because the brokers need to know the IP addresses of the node where the NameServer services are deployed on, so that the brokers could communicate with the NameServer services clusters.

**Comment by Kaijun** [comment]
> Because the brokers need to know the IP addresses of the node where the namesrv(NameServer) services are deployed on, so that the brokers could communicate with the namesrv services clusters.
> 
> However, this configuration step is for the first time when initialize the broker cluster. When up-scale the namesrv cluster, the new IP list of the namesrv cluster is automatically maintained and told to the broker cluster.

why not using `kubernetes service dns` istead of static IP?

**Comment by Kaijun** [comment]
I have to create nameserver in the first place, and extract the ip which nameserver is using, then finally  i could fill it into broker cr.

**Comment by Kaijun** [comment]
I have to create nameserver in the first place, and extract the ip which nameserver is using, then finally i could fill it into broker cr.

the order of deploying makes it not possible to deploy a complete rocketmq service the way by using a simple stack. it's also kind of against the philosophy of kubernetes which emphasizes state oriented.

@liuruiyiyang @vongosling

**Comment by duhenglucky** [comment]
@Kaijun use the DNS will be a better choice, so would you like to submit a PR to polish it?

**Comment by hzliangbin** [comment]
@duhenglucky @Kaijun According to the blog of  AliMiddleware, the nameserver cluster  is decentralization. And each broker will connect to all nameservers to refresh broker's info. It's OK when NameServer' size is 1. kubernetes service will always lead to one backend pod. 

But  when there are 2 or more nameservers, the kubernetes service will forward to  only one of the backend pods based on some loadbanlance strategy. 

A not that perfect solution :
if you have 3 nameservers you should create 3 services. Each service targets exactly one pod. The brokers use servicename instead IP to register to namerservers.

**Comment by vongosling** [comment]
This issue has been closed because it has not had activity in the last 30 days. If this issue is still valid, please ping a committer and ask them to label it as "help wanted". Thank you for your contributions.
