### ISSUE TITLE
broker GC log files filling up sandboxes disk space

### ISSUE THREAD

**Issue by stringang** [apache/rocketmq-operator#177]
1. Please describe the issue you observed:
 
     After the `broker` has been running for a while, the `shm` on the host sends out a space-filling alarm.

     the mount point for `shm` is `/data/containerd/state/io.containerd.grpc.v1.cri/sandboxes/4da84135c521f12560742f0739783dea5687503667f81f32a56d9f0f52b0784f/shm`.

     going into the `shm` directory, I found the directory to be the gc log.

2. Please tell us about your environment:
    - kubernetes: v1.22.15
    - apacherocketmq/rocketmq-broker:4.5.0-alpine-operator-0.3.0
    - containerd: v1.5.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
  
<img width="1226" alt="image" src="https://github.com/apache/rocketmq-operator/assets/14845458/3ae6863f-9df9-46a6-bc4b-f8aeaaf9b63f">

<img width="1551" alt="image" src="https://github.com/apache/rocketmq-operator/assets/14845458/ab006ba6-09cc-4e12-9029-914138eef0c8">

<img width="1181" alt="image" src="https://github.com/apache/rocketmq-operator/assets/14845458/0e6dc29a-9227-4529-88dd-6238f9f6d215">

**Comment by caigy** [comment]
The default `shm-size` of docker is ~64MB, but the broker can generate at most 5 GC logs, each consumes 30MB.
Workaround may be one of the following:

- limit `NumberOfGCLogFiles` and `GCLOGFileSize`;
- specify `-Xloggc` as a path of broker logs.

**Comment by stringang** [comment]
thanks @caigy
