### ISSUE TITLE
deploy the RocketMQ broker clusters  error

### ISSUE THREAD

**Issue by hppx5456** [apache/rocketmq-operator#19]
when i use command 
kubectl apply -f example/rocketmq_v1alpha1_broker_cr.yaml
kubectl get pods -owide
my clusters status is:
broker-0-master-0                    0/1     CrashLoopBackOff   6          11m    10.244.1.7     k8s-node1    <none>           <none>
broker-0-replica-1-0                 0/1     CrashLoopBackOff   6          11m    10.244.1.6     k8s-node1    <none>           <none>
curl-69c656fd45-94qbj                1/1     Running            1          107m   10.244.0.4     k8s-master   <none>           <none>
name-service-0                       1/1     Running            0          12m    30.26.223.45   k8s-node1    <none>           <none>
rocketmq-operator-648b54b558-tgb72   1/1     Running            1          81m    10.244.1.2     k8s-node1    <none>           <none>

**Comment by vongosling** [comment]
This issue has been closed because it has not had activity in the last 30 days. If this issue is still valid, please ping a committer and ask them to label it as "help wanted". Thank you for your contributions.

**Comment by walk1ng** [comment]
Hi @vongosling , 
I have the same issue. the broker pods were terminated by reason of **OOMKilled**.
I have try to provide more memory with `spec.resources.limits.memory` but still failed, could you please help?
Thanks.

**Comment by liuruiyiyang** [comment]
@walk1ng  Try to set  spec.resources.limits.memory more than 10GB and see if it works.

**Comment by walk1ng** [comment]
> @walk1ng Try to set spec.resources.limits.memory more than 10GB and see if it works. In the current master branch we set memory resource limit to 12GB in broker CRD example yaml config. Read the README doc and there is a notice about this problem, which may help you.

ok, thanks!
