### ISSUE TITLE
broker使用hostNetwork: true，但是注册到name-service上的IP还是pod CIDR段的IP

### ISSUE THREAD

**Issue by yylstudy** [apache/rocketmq-operator#202]
1. Please describe the issue you observed:

broker使用hostNetwork: true，但是注册到name-service上的IP还是pod CIDR段的IP
broker配置如下
![image](https://github.com/apache/rocketmq-operator/assets/26402953/be20fad3-b89c-4f99-a97e-c9e80bb6fa8c)
broker启动后ip也为节点IP
![image](https://github.com/apache/rocketmq-operator/assets/26402953/1bb33039-63e3-4387-b590-39c74233c04a)
查看dashboard上的broker 仍然为pod的CIDR段IP
![image](https://github.com/apache/rocketmq-operator/assets/26402953/cb395b78-9503-407c-a4f1-40b329a2f363)

broker日志也是CIDR段的IP
![image](https://github.com/apache/rocketmq-operator/assets/26402953/24e167b2-a2a6-46c9-b05e-bb4cd2dca4d4)
 

2. Please tell us about your environment:
k8s：1.23.6
网络插件:cilium
rocketmq-operator：采用helm部署，版本为0.3.0
broker镜像版本apacherocketmq/rocketmq-broker:4.5.0-alpine-operator-0.3.0

请问下为什么会出现这个问题呢，是不是和broker的镜像有关系，谢谢。

**Comment by shangjin92** [comment]
Yes, it may be related to the broker image, where you need to set the brokerIP1 parameter. Please see  https://rocketmq.apache.org/docs/4.x/parameterConfiguration/02server/

![image](https://github.com/apache/rocketmq-operator/assets/7251928/15754410-5e33-4ef9-a73c-016a36320418)

**Comment by yylstudy** [comment]
这个不能设置brokerIP1吧，在broker hostNetwork为true的情况下，如果获取到的是节点IP，那么外部就能访问到了
