### ISSUE TITLE
Add addtional action to repository

### ISSUE THREAD

**Issue by drivebyer** [apache/rocketmq-operator#206]
In #190, I aim to add a workflow that runs E2E tests for every PR. This workflow may require certain actions to set up the test environment, such as installing a Kind cluster or testing tools like Chainsaw. However, it appears that the repository does not allow these actions, as seen at https://github.com/apache/rocketmq-operator/actions/runs/7348942797. Therefore, I suggest adding these actions to the allowed list.

**Comment by drivebyer** [comment]
cc @caigy  @RongtongJin

**Comment by caigy** [comment]
@drivebyer It seems those limits are set by Apache. Similar problems are encountered in other communities: 

- https://github.com/apache/shardingsphere-on-cloud/issues/71

**Comment by caigy** [comment]
@drivebyer The document below introduces e2e testing for operator sdk, it might be helpful:

- https://sdk.operatorframework.io/docs/building-operators/golang/testing/

**Comment by drivebyer** [comment]
> @drivebyer The document below introduces e2e testing for operator sdk, it might be helpful:
> 
> * https://sdk.operatorframework.io/docs/building-operators/golang/testing/

OK.

**Comment by drivebyer** [comment]
I closed it, becouse it be workaround by https://github.com/apache/rocketmq-operator/pull/211.
