### ISSUE TITLE
 What is the difference between brokerName and brokerClusterName

### ISSUE THREAD

**Issue by zhihui921016** [apache/rocketmq-operator#21]
The issue tracker is **ONLY** used for the bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before you raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Why does brokerClusterName need to be suffixed with "brokerGroupIndex"? As I understand it, one cluster contains multiple brokers
![image](https://user-images.githubusercontent.com/25976014/75410710-bad88400-5957-11ea-9f7e-0c3241a621cb.png)

- What did you expect to see?
brokerClusterName removes the brokerGroupIndex suffix

- What did you see instead?
brokerClusterName is suffixed with "brokerGroupIndex"

2. Please tell us about your environment:
operator:0.2.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by hxnan** [comment]
I am confusing with the brokerClusterName too.

**Comment by hxnan** [comment]
I prefer to set the clusterName in `broker.Spec.ClusterName`
