### ISSUE TITLE
Type Conversion in broker test 

### ISSUE THREAD

**Issue by AdheipSingh** [apache/rocketmq-operator#27]
**BUG REPORT**

1. Please describe the issue you observed:
- In line https://github.com/apache/rocketmq-operator/blob/master/pkg/controller/broker/broker_controller_test.go#L59 
Size has type int where as replicas is of type int32. Ideally this should be 
```
Size: int(replicas)
```

**Comment by liuruiyiyang** [comment]
Thanks for your report, we will correct it in newer version.
