### ISSUE TITLE
question about namesrv cluster up-scale

### ISSUE THREAD

**Issue by keranbingaa** [apache/rocketmq-operator#28]
when namesrv cluster up-scaling，does the broker shutdown and change the namesrv list and then restart?
I have this question becuase I  note the broker IP changed after namesrv cluster up-scale and the log file contians restart log. can we up-scale the namesrv cluster without restart broker?

**Comment by liuruiyiyang** [comment]
YES, when namesrv cluster up-scaling, the broker instances will rolling restart (one by one). Thus this process has little influence on providing service for user bussiness.
Could you please tell us more about what harms if the broker restart in your application scenario?

**Comment by liuruiyiyang** [comment]
In fact we have considered this question and you can refer to RocketMQ PR#1458[https://github.com/apache/rocketmq/pull/1458]

**Comment by keranbingaa** [comment]
> In fact we working on this and you can refer to RocketMQ PR#1458[https://github.com/[apache/rocketmq/pull/1458](https://github.com/apache/rocketmq/pull/1458)]
ok,I will refer to this
