### ISSUE TITLE
Save the configuration of the broker cluster and jvm in the ConfigMap

### ISSUE THREAD

**Issue by zhihui921016** [apache/rocketmq-operator#29]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Save the configuration of the broker cluster and jvm in the ConfigMap

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
The current configuration information is stored in the image, we have to rebuild the image every time we modify the configuration. Saving the configuration in ConfigMap is a better choice

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by liuruiyiyang** [comment]
see PR #25
