### ISSUE TITLE
rbd mount /root/logs and /root/store problem when using ceph storage class

### ISSUE THREAD

**Issue by fengjian1585** [apache/rocketmq-operator#37]
![image](https://user-images.githubusercontent.com/16216965/90366783-4ecf1100-e09a-11ea-86d0-43a236322b73.png)
![image](https://user-images.githubusercontent.com/16216965/90366841-67d7c200-e09a-11ea-8729-be938f63e2f6.png)

**Comment by liuruiyiyang** [comment]
Could you please describe more about your problem?

**Comment by caigy** [comment]
Could you describe this issue in details? Is it a problem about ceph storage plugins or operator itself?

**Comment by caigy** [comment]
@fengjian1585 Any updates?

**Comment by caigy** [comment]
This issue may be outdated so I'll close it first. Feel free to reopen if the problem still exists.
