### ISSUE TITLE
Hope rocketmq-operator could provide configs to set IP exposed to the outside (k8s implemented mutil-cni, affiliate network use macvlan)

### ISSUE THREAD

**Issue by z5614036** [apache/rocketmq-operator#40]
k8s实现mutil-cni，附属网络是macvlan。希望rocketmq-operator，可以指定暴露给外部的ip。  我不用主网络，而是使用macvlan附属网络。  希望增加新功能

**Comment by caigy** [comment]
Currently hostNetwork can be set to 'true' for name servers and brokers in  rocketmq-operator, this issue can be resolved. If not so, please feel free to reopen it and provide more detail information.
