### ISSUE TITLE
kubectl apply -f  example/rocketmq_v1alpha1_rocketmq_cluster.yaml nameservice.rocketmq.apache.org/name-service created The Broker "broker" is invalid:  * spec.env: Required value * spec.volumes: Required value

### ISSUE THREAD

**Issue by DevOpserzhao** [apache/rocketmq-operator#43]
kubectl apply -f  example/rocketmq_v1alpha1_rocketmq_cluster.yaml
nameservice.rocketmq.apache.org/name-service created
The Broker "broker" is invalid: 
* spec.env: Required value
* spec.volumes: Required value

**Comment by liuruiyiyang** [comment]
If you are using the master branch which is not stable currently because recently we are adding some apis, I suggest you checkout to release tag v0.2.1 and follow the README see if it works. :)

**Comment by liuruiyiyang** [comment]
This problem should be fixed by PR#46.
