### ISSUE TITLE
I can't deploy the operator

### ISSUE THREAD

**Issue by yhz1985** [apache/rocketmq-operator#58]
I deploy the install-operator.sh
but it's error
![image](https://user-images.githubusercontent.com/19431363/93965193-135bec80-fd94-11ea-84e4-c8e7935b3fac.png)
what's happened?

**Comment by linjiemiao** [comment]
ErrorMessage: If kind is a CRD, it should be installed before calling Start. I think your operator watch&list Console Resource, but this resource is not in the master branch.

I think you may need to rebuild the image of the operator and then replace the image field in deploy/operator.yaml.
You can use ./create-operator.sh to build the image, but attention to the address of the image repository.

**Comment by liuruiyiyang** [comment]
@yhz1985 It is because I have updated the operator image but has not merged the code to the master branch yet. Now it should be fixed  since I have merge PR #53 .
