### ISSUE TITLE
需要重新打包broker镜像

### ISSUE THREAD

**Issue by hellohaoyalong** [apache/rocketmq-operator#59]
原有配置文件生成脚本中，$BROKER_CONFIG_MOUNT_FILE指向文件不存在

**Comment by hellohaoyalong** [comment]
BROKER_CONFIG_FILE="$ROCKETMQ_HOME/conf/broker.conf"
BROKER_CONFIG_MOUNT_FILE="$ROCKETMQ_HOME/conf/broker-common.conf"

function create_config() {
    rm -f $BROKER_CONFIG_FILE
    echo "Creating broker configuration."
    # Remove brokerClusterName, brokerName, brokerId if configured
    ### sed -e '/brokerClusterName/d;/brokerName/d;/brokerId/d' $BROKER_CONFIG_MOUNT_FILE > $BROKER_CONFIG_FILE
    echo -e >> $BROKER_CONFIG_FILE
    echo "brokerClusterName=$BROKER_CLUSTER_NAME" >> $BROKER_CONFIG_FILE
    echo "brokerName=$BROKER_NAME" >> $BROKER_CONFIG_FILE
    echo "brokerId=$BROKER_ID" >> $BROKER_CONFIG_FILE
    if [ $BROKER_ID != 0 ]; then
        sed -i 's/brokerRole=.*/brokerRole=SLAVE/g' $BROKER_CONFIG_FILE
    fi
}

create_config

**Comment by liuruiyiyang** [comment]
I have checked that the $BROKER_CONFIG_MOUNT_FILE did exists, it is mounted by broker-config ConfigMap.
