### ISSUE TITLE
无法在其他命名空间创建资源成功

### ISSUE THREAD

**Issue by ziyouguodu** [apache/rocketmq-operator#64]
无法在其他命名空间创建资源成功，只能在default下才能创建nameservice 和broker资源对象

**Comment by nogoodbay** [comment]
你需要将operator、service_account、role、role_binding在你需要部署的命名空间中重新创建一下。
重新创建的方式是修改deploy目下下对应的4个yaml文件，添加你的命名空间，然后分别执行`kubelet apply -f `

**Comment by ziyouguodu** [comment]
好的，我试试，谢谢

**Comment by RobertoHuang** [comment]
遇到同样问题 按楼上说的已解决
