### ISSUE TITLE
Hope to support external client of K8S cluster access

### ISSUE THREAD

**Issue by RobertoHuang** [apache/rocketmq-operator#66]
有时候客户端并不是使用K8S进行部署，或者客户端和RocketMQ部署在不同的K8S集群

目前RocketMQ往NameServer注册的地址是PodIP导致集群外无法访问到，希望能得到支持

**Comment by walk1ng** [comment]
the same feature request as @RobertoHuang, hope the team to support it, thanks! @RongtongJin

**Comment by duhenglucky** [comment]
> 有时候客户端并不是使用K8S进行部署，或者客户端和RocketMQ部署在不同的K8S集群
> 
> 目前RocketMQ往NameServer注册的地址是PodIP导致集群外无法访问到，希望能得到支持

是overlay 网络的支持吗？如果是独占部署的，是否可以采用host 的模式来解决这个问题

**Comment by liruishan** [comment]
> > 有时候客户端并不是使用K8S进行部署，或者客户端和RocketMQ部署在不同的K8S集群
> > 目前RocketMQ往NameServer注册的地址是PodIP导致集群外无法访问到，希望能得到支持
> 
> 是overlay 网络的支持吗？如果是独占部署的，是否可以采用host 的模式来解决这个问题

我目前使用的nameserver是hostnetwork方式部署，但是broker不是这种方式部署，我从集群外可以访问到nameserver，但是无法访问到broker，仍然无法使用外部客户端；
后来我将nameserver和broker都通过hostnetwork方式部署，但是producer仍然无法跟broker建立连接。
我想问一下，k8s部署的方式，是不是不支持集群外的客户端访问？

**Comment by MrLYG** [comment]
> > > 有时候客户端并不是使用K8S进行部署，或者客户端和RocketMQ部署在不同的K8S集群
> > > 目前RocketMQ往NameServer注册的地址是PodIP导致集群外无法访问到，希望能得到支持
> > 
> > 
> > 是overlay 网络的支持吗？如果是独占部署的，是否可以采用host 的模式来解决这个问题
> 
> 我目前使用的nameserver是hostnetwork方式部署，但是broker不是这种方式部署，我从集群外可以访问到nameserver，但是无法访问到broker，仍然无法使用外部客户端； 后来我将nameserver和broker都通过hostnetwork方式部署，但是producer仍然无法跟broker建立连接。 我想问一下，k8s部署的方式，是不是不支持集群外的客户端访问？

虽然broker配置了hostNetwork 但是同一集群间的pod沟通是通过cni来沟通的。 namesver 会把broker的路由配置成相应cni的ip，这个ip 在集群外也是无法访问的。

**Comment by feixiaohuijava** [comment]
> 

Any idea  to connect broker out of cluster?

**Comment by caigy** [comment]
In my opinion, adopting host network should work, brokerIP should also be configured as host ip.

**Comment by caigy** [comment]
#105 may resolve this problem.
