### ISSUE TITLE
Operator is not usefull cross namespaces

### ISSUE THREAD

**Issue by yockliu** [apache/rocketmq-operator#68]
I follow the Operatorhub installation instruction (https://operatorhub.io/operator/rocketmq-operator):

1、curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0
2、kubectl create -f https://operatorhub.io/install/rocketmq-operator.yaml

Below the instruction, it says: "This Operator will be installed in the "operators" namespace and will be usable from all namespaces in the cluster."

But when I create NameService And Broker, only works in the namespace operators, it will create deployment and services. In other namespaces, nothing happened.

ENV: Aliyun K8S 1.18

**Comment by vongosling** [comment]
ping @liuruiyiyang

**Comment by yockliu** [comment]
咋说，在k8s上，我能用rocketmq-operator吗，还是你们推荐其他的部署方式

**Comment by chilejiang1024** [comment]
确实有这个问题啊 
operator 默认创建在default namespace下 
但是不想把东西安装到default下 
加了 namespace 后, kubectl apply 就没反应了

**Comment by lizhiboo** [comment]
> I follow the Operatorhub installation instruction (https://operatorhub.io/operator/rocketmq-operator):
> 
> 1、curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0
> 2、kubectl create -f https://operatorhub.io/install/rocketmq-operator.yaml
> 
> Below the instruction, it says: "This Operator will be installed in the "operators" namespace and will be usable from all namespaces in the cluster."
> 
> But when I create NameService And Broker, only works in the namespace operators, it will create deployment and services. In other namespaces, nothing happened.
> 
> ENV: Aliyun K8S 1.18

IMO, it's authority problem. use ClusterRole instead of Role will works.

**Comment by yaphetsglhf** [comment]
> > I follow the Operatorhub installation instruction (https://operatorhub.io/operator/rocketmq-operator):
> > 1、curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/install.sh | bash -s v0.17.0
> > 2、kubectl create -f https://operatorhub.io/install/rocketmq-operator.yaml
> > Below the instruction, it says: "This Operator will be installed in the "operators" namespace and will be usable from all namespaces in the cluster."
> > But when I create NameService And Broker, only works in the namespace operators, it will create deployment and services. In other namespaces, nothing happened.
> > ENV: Aliyun K8S 1.18
> 
> IMO, it's authority problem. use ClusterRole instead of Role will works.

i modify the role to clusterrole, it doesn't work.

**Comment by yaphetsglhf** [comment]
Temprary, solve the problem by deploy multi operators in different ns.

**Comment by lijilina** [comment]
> 确实有这个问题啊
> operator 默认创建在default namespace下
> 但是不想把东西安装到default下
> 加了 namespace 后, kubectl apply 就没反应了

我也是这个问题

**Comment by chawanbid** [comment]
role是单一名称空间，如果要在其他namaspace下创建，需要把role换成clusterrole。这点很不友好

**Comment by chawanbid** [comment]
> > 确实有这个问题啊
> > operator 默认创建在default namespace下
> > 但是不想把东西安装到default下
> > 加了 namespace 后, kubectl apply 就没反应了
> 
> 我也是这个问题

role问题，需要自己创建clusterrole，然后进行clusterrole_binding对应的serviceaccount绑定clusterrole

**Comment by xuzhzz** [comment]
我看这个operator共享了好几个全局变量，https://github.com/apache/rocketmq-operator/blob/master/pkg/share/share.go

**Comment by xuzhzz** [comment]
我看这个operator共享了好几个全局变量，https://github.com/apache/rocketmq-operator/blob/master/pkg/share/share.go，我理解成一个operator只能支持一个rocketmq集群，似乎不支持跨namespace多rocketmq集群。

**Comment by xuzhzz** [comment]
我看这个operator共享了好几个 [全局变量](https://github.com/apache/rocketmq-operator/blob/master/pkg/share/share.go)，我理解成一个operator只能支持一个rocketmq集群，似乎不支持跨namespace多rocketmq集群？

**Comment by caigy** [comment]
IMO it has been supported in the latest version.

**Comment by drivebyer** [comment]
It seems that still created resource in default namespace: https://github.com/apache/rocketmq-operator/blob/ac9804643989fd2983c5c90fcb2c084d78cead47/deploy/operator.yaml#L18-L19
