### ISSUE TITLE
是否支持更高的版本

### ISSUE THREAD

**Issue by lx308033262** [apache/rocketmq-operator#69]
现在我看官网的镜像operator最高是4.5，是否可以支持4.6版本？

**Comment by vongosling** [comment]
Do you have any problems with 4.5?

**Comment by lx308033262** [comment]
yes  i  want to use  “ Request-Reply " feature

**Comment by lx308033262** [comment]
but  i create 4.7 image by myself  ( just download  docker image  and replace  rocket package  and modify some script )
thank you
