### ISSUE TITLE
Dockerfile issue

### ISSUE THREAD

**Issue by huanwei** [apache/rocketmq-operator#7]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
./create-operator.sh 
- What did you expect to see?
operator image built with success
- What did you see instead?
operator image built with error, as following:
```
INFO[0000] Building OCI image docker.io/library/rocketmq-operator:v0.0.1-snapshot 
Sending build context to Docker daemon  70.62MB
Step 1/15 : FROM openjdk:8-alpine
 ---> a3562aa0b991
Step 2/15 : RUN apk add --no-cache bash gettext nmap-ncat openssl busybox-extras
 ---> Using cache
 ---> f589b44cfa81
Step 3/15 : ENV OPERATOR=/usr/local/bin/rocketmq-operator     USER_UID=1001     USER_NAME=rocketmq-operator
 ---> Using cache
 ---> cc4ea4c26514
Step 4/15 : COPY build/_output/bin/rocketmq-operator ${OPERATOR}
 ---> Using cache
 ---> 4a1a344fd240
Step 5/15 : COPY build/bin /usr/local/bin
 ---> Using cache
 ---> 7579aed2506c
Step 6/15 : RUN  /usr/local/bin/user_setup
 ---> Using cache
 ---> 3d3e29904d3d
Step 7/15 : ENV ROCKETMQ_VERSION 4.5.0
 ---> Using cache
 ---> bb839b99a39c
Step 8/15 : ENV ROCKETMQ_HOME  /home/rocketmq/rocketmq-${ROCKETMQ_VERSION}
 ---> Using cache
 ---> 43ff35f63e5f
Step 9/15 : WORKDIR  ${ROCKETMQ_HOME}
 ---> Using cache
 ---> 9ef1be398427
Step 10/15 : COPY build/rocketmq.zip ${ROCKETMQ_HOME}/rocketmq.zip
COPY failed: stat /var/lib/docker/tmp/docker-builder520479874/build/rocketmq.zip: no such file or directory
Error: failed to output build image docker.io/library/rocketmq-operator:v0.0.1-snapshot: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "docker.io/library/rocketmq-operator:v0.0.1-snapshot", "."}: exit status 1)
```
2. Please tell us about your environment:
linux
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
Why did we install rocketmq code in operator? I suggest removing the unused parts.

**Comment by liuruiyiyang** [comment]
Thanks for your questions.

Currently the ```rocketmq-operator``` and other related images has not been pushed to the ```docker.io/library``` repo, but we will push the images to the official docker repo in the future. You may consider ```docker.io/library``` as a placeholder for now, which you can replace it with your own repo for development and testing purpose. We will mention this in the documents for developers later.

For the rocketmq code, the operator will collaborate with the ```RocketMQ Admin Tool``` to do the cluster management jobs so we simply install rocketmq code in the operator image. We haven't separated the ```mqadmin``` related part yet, welcome to do some optimizations on that.
