### ISSUE TITLE
how to use k8s.io/code-generator for  generating rocketmq-operator apis

### ISSUE THREAD

**Issue by bubei-inc** [apache/rocketmq-operator#72]
执行如下命令：
>  /src/k8s.io/code-generator/generate-groups.sh all github.com/apache/rocketmq-operator/client  github.com/apache/rocketmq-operator/pkg/apis "rocketmq:v1alpha1" 

生成如下图：

![image](https://user-images.githubusercontent.com/33147297/109632876-768f4d80-7b82-11eb-9317-d269227daa93.png)

问题：
未生成rocketmq-operator相关的操作 如 List ，Create , Get......

**Comment by caigy** [comment]
The version of operator framework has been updated and the commands above are not available. Please try the latest version.
