### ISSUE TITLE
How to customize the rocketmq-dashboard configuration

### ISSUE THREAD

**Issue by Euthpic** [apache/rocketmq-operator#73]
I follow the installation instruction(https://segmentfault.com/a/1190000023862693) to install rocketmq in k8s.
Now I want to change rocketmq's default configuration to enable console's password.
Operation(https://github.com/apache/rocketmq-externals/blob/master/rocketmq-console/doc/1_0_0/UserGuide_CN.md):
``
1.在Spring配置文件resources/application.properties中修改 开启登录功能
# 开启登录功能
rocketmq.config.loginRequired=true

# Dashboard文件目录，登录用户配置文件所在目录
rocketmq.config.dataPath=/tmp/rocketmq-console/data
2.确保${rocketmq.config.dataPath}定义的目录存在，并且该目录下创建登录配置文件"users.properties", 如果该目录下不存在此文件，则默认使用resources/users.properties文件。 users.properties文件格式为:
# 该文件支持热修改，即添加和修改用户时，不需要重新启动console
# 格式， 每行定义一个用户， username=password[,N]  #N是可选项，可以为0 (普通用户)； 1 （管理员）  

#定义管理员 
admin=admin,1

#定义普通用户
user1=user1
user2=user2
``
But I dont konw how to find this two files and edit them.Should I inject them by adding configMap?

**Comment by Euthpic** [comment]
Env : 
  k8s : Tencent Cloud v1.18.4-tke.6
  rocketmq: 4.5.0

**Comment by caigy** [comment]
@Euthpic `resources/application.properties` is in source code of [rocketmq-dashboard](https://github.com/apache/rocketmq-dashboard), please check if it can be injected by environment variables. For `users.properties`, you should create one and put it the folder `${rocketmq.config.dataPath}` defined.

However, rocketmq operator does not support mounting a configMap to rocketmq-dashboard, would you like to submit a PR to solve it?

**Comment by Slideee** [comment]
> @Euthpic `resources/application.properties` is in source code of [rocketmq-dashboard](https://github.com/apache/rocketmq-dashboard), please check if it can be injected by environment variables. For `users.properties`, you should create one and put it the folder `${rocketmq.config.dataPath}` defined.
> 
> However, rocketmq operator does not support mounting a configMap to rocketmq-dashboard, would you like to submit a PR to solve it?

I think you can mount application.properties, users.properties with ConfigMap, so as to achieve the purpose of modifying the dashboard configuration. If possible, I would like to submit relevant code to solve this problem in the near future.

**Comment by zongtanghu** [comment]
Can you put forward a pr to support this feature? If you have any question, I will help to fix and implement it!

**Comment by zongtanghu** [comment]
Okay, it's yours! @shendongsd
