### ISSUE TITLE
unable to recognize "deploy/crds/rocketmq_v1alpha1_broker_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by carloscao0928** [apache/rocketmq-operator#78]
kubectl version v1.22.0

root@xxx:~/rocketmq-operator# bash -x install-operator.sh 
+ kubectl create -f deploy/crds/rocketmq_v1alpha1_broker_crd.yaml
error: unable to recognize "deploy/crds/rocketmq_v1alpha1_broker_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
+ kubectl create -f deploy/crds/rocketmq_v1alpha1_nameservice_crd.yaml
error: unable to recognize "deploy/crds/rocketmq_v1alpha1_nameservice_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
+ kubectl create -f deploy/crds/rocketmq_v1alpha1_consoles_crd.yaml
error: unable to recognize "deploy/crds/rocketmq_v1alpha1_consoles_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
+ kubectl create -f deploy/crds/rocketmq_v1alpha1_topictransfer_crd.yaml
error: unable to recognize "deploy/crds/rocketmq_v1alpha1_topictransfer_crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
+ kubectl create -f deploy/service_account.yaml
serviceaccount/rocketmq-operator created
+ kubectl create -f deploy/role.yaml
role.rbac.authorization.k8s.io/rocketmq-operator created
+ kubectl create -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io/rocketmq-operator created

**Comment by Hatuw** [comment]
You should migrate the yaml file to `apiVersion: apiextensions.k8s.io/v1`
see also, https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22

**Comment by jisongxi** [comment]
only change the yaml  to apiVersion: apiextensions.k8s.io/v1, casue another issue like this : The CustomResourceDefinition "brokers.rocketmq.apache.org" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
how to fix this issue in k8s 1.22 version?

**Comment by caigy** [comment]
fixed by #97
