### ISSUE TITLE
nameservice restart continuously 

### ISSUE THREAD

**Issue by overstep123** [apache/rocketmq-operator#84]
the nameservice pod restart continuously because of OOM 

**BUG REPORT**

1. Please describe the issue you observed:

- startup a rocketmq cluster with rocketmq-operator,and set a small memory resource limit for nameservice

- run Normally

- the nameservice pod restart continuously because of OOM

**Comment by caigy** [comment]
It seems that requested memory defined is too small.

**Comment by caigy** [comment]
fixed by #81
