### ISSUE TITLE
How do I configure my own broker configuration file in crd?

### ISSUE THREAD

**Issue by zouchengli** [apache/rocketmq-operator#86]
Because I want to install the rocket dashboard, but because the broker’s configuration file is automatically generated by the operator, I cannot modify the listening port and naming service. This will cause my dashboard to fail to monitor it. Is there a way to fix this problem?

**Comment by caigy** [comment]
If configurations you want to change are exposed as environment variables, you can set them in `env` part of specific custom resources.
