### ISSUE TITLE
K8s higher api version support 

### ISSUE THREAD

**Issue by BeiCity** [apache/rocketmq-operator#91]
**BUG REPORT**

1. 问题一:
我执行脚本文件命令:
kubectl create -f deploy/crds/rocketmq_v1alpha1_broker_crd.yaml
然后报错:
error: error validating "rocketmq_v1alpha1_broker_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

2. 问题二:
版本问题什么时候能更新呢
![image](https://user-images.githubusercontent.com/46420720/154394358-96bb8158-ab15-46eb-a855-f3b8922832be.png)

**Comment by waney316** [comment]
是不是k8s版本问题，我执行没有问题

**Comment by BeiCity** [comment]
> 是不是k8s版本问题，我执行没有问题

我的版本是v.1.22.3

**Comment by xjdtd** [comment]
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition   1.22版本以后v1beta1就无效了

**Comment by xjdtd** [comment]
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition   1.22版本以后v1beta1就无效了
但是现在使用v1版的话，会报好多字段找不到
error: error validating "deploy/crds/rocketmq_v1alpha1_broker_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]

**Comment by caigy** [comment]
fixed by #97
