### ISSUE TITLE
load subscriptionGroup.json syntax error, expect {

### ISSUE THREAD

**Issue by waney316** [apache/rocketmq-operator#93]
when i delelte pod then pod cannot start，broker log hava erros to load topic.json or subscriptionGroup.json
![image](https://user-images.githubusercontent.com/23314093/156995391-b6567952-bbbb-4978-b179-0d4b551529b5.png)

**Comment by caigy** [comment]
It seems that it may be resolved by #82 , could you have a try?

**Comment by waney316** [comment]
It is not clear how to reproduce this problem，so I haven't tried
